name: My First Action
on: push
jobs:
    my_first_action:
        name: My First Action
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: test my workflow
              run: |
                npm install
                npm run test